import type {Metadata} from 'next';
import {Geist, Geist_Mono, Outfit} from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';
import Sidebar from '@/components/Sidebar/Sidebar';
import {ReactNode} from 'react';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const outfit = Outfit({
    variable: '--font-outfit',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${outfit.className} antialiased grid min-h-screen grid-cols-[20%_minmax(0,1fr)_20%] bg-gray-900 text-gray-100 p-6`}
            >
                <Navigation className={'sticky top-0 bottom-0 border-r border-gray-800'}/>
                {children}
                <Sidebar className={'sticky top-0 bottom-0 border-l border-gray-800'}/>
            </body>

        </html>
    );
}
